### PR TITLE
auth. added

### PR DESCRIPTION
**Pull request by Fran-Va**
hey guys 
I received the following error message: 

== 20240308115303 AddDeviseToUsers: migrating =================================
-- change_table(:users)
bin/rails aborted!
StandardError: An error has occurred, this and all later migrations canceled:

PG::DuplicateColumn: ERROR:  column "email" of relation "users" already exists
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:7:in `block in up'
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:5:in `up'

Caused by:
ActiveRecord::StatementInvalid: PG::DuplicateColumn: ERROR:  column "email" of relation "users" already exists
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:7:in `block in up'
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:5:in `up'

Caused by:
PG::DuplicateColumn: ERROR:  column "email" of relation "users" already exists
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:7:in `block in up'
/Users/francesca/code/Fran-Va/passbridge/db/migrate/20240308115303_add_devise_to_users.rb:5:in `up'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)

I saw that there is are two files 
- 20240301104758_devise_create_users.rb. 
- 20240308115303_add_devise_to_users.rb 

which one is the correct one? 

Thanks!
Francesca

### CODE REVIEW

**Comment by GianClaudioScarafini** [comment]
I think this is related to the fact that you were trying to add a user email when is already there. 

please use the forum if you have questions :)

**Comment by GianClaudioScarafini** [comment]
@Fran-Va  have you solve that issue that you raised with a TA?

**Comment by Fran-Va** [comment]
> @Fran-Va have you solve that issue that you raised with a TA?

Yes. Arbi told me that the devise is always one of the first things you do. And since someone else set it up before me, I have created a duplicate migration. It's correct how it is in the master at least the migration device file which is why I'm going to delete the other migration devise file I created.

**Comment by Fran-Va** [comment]
@GianClaudioScarafini can you please resolve the conflicts here? :)

**Comment by GianClaudioScarafini** [comment]
I was not me it was the TA

**Pull request closed without merging**
